### ISSUE TITLE
Time is a resource

### ISSUE THREAD

**Issue by frobnitzem** [ExaWorks/job-api-spec#174]
**Describe the error, inconsistency, or unclear wording here**

Job metadata is split into resources and attributes.  However, time (job duration) is incorrectly categorized as an attribute:
https://github.com/ExaWorks/job-api-spec/blob/main/specification.md#jobattributes

Schedulers require time information on jobs because the resource allocation problem is a 2-dimensional packing problem: nodes by time.

### Suggested Clarification

Job duration should be moved into the ResourceSpec.

**Comment by hategan** [comment]
Thank you for the suggestion.

The job duration may not be unique in this, but some things are somewhat ambiguous. It is entirely possible for a job to have an estimated duration of x but to request an allocation for a different time, y. There are some other examples like that, such as mpi jobs that need a particular number of ranks: this is both a property/attribute of the job and a dimension in a resource request.

The duration is currently a job attribute because 1) for simplicity, we didn't want to have a separate allocation time parameter, especially because on batch queuing systems the most frequent interpretation of the duration is the desired allocation time and 2) because it may be useful beyond resource specifications for a batch system; for example, it can be (and has been) used in workflow systems to determine whether a job is exhibiting anomalous behavior and terminate it.

**Comment by andre-merzky** [comment]
I have no real preference for the time attribute - if no decisive argument can be made to favor one option over the other I all am for leaving things as they are though.

But would like to pick up on this statement:

> such as mpi jobs that need a particular number of ranks: this is both a property/attribute of the job and a dimension in a resource request.

The number of ranks I clearly see as a job attribute.  Resources don't have ranks, but rather, well, resources: cores, hw-threads, GPUs, memory etc.  How those resources are then subdivided between ranks of the application is a whole different story - and usually part of the *job* layout across the requested resources.

**Comment by hategan** [comment]
> > such as mpi jobs that need a particular number of ranks: this is both a property/attribute of the job and a dimension in a resource request.
> 
> The number of ranks I clearly see as a job attribute. Resources don't have ranks, but rather, well, resources: cores, hw-threads, GPUs, memory etc. How those resources are then subdivided between ranks of the application is a whole different story - and usually part of the _job_ layout across the requested resources.

That's a fair point and I think we had some discussion a while back on all the complexities of mapping what the job is to what the resources are, which is why we envisioned more complex ResourceSpec versions.
But if I understand correctly, what you are somewhat suggesting is that some things in ResourceSpec, such as the process count, should be in JobAttributes. I would make me feel better about the lone `duration` problem...

**Comment by andre-merzky** [comment]
> But if I understand correctly, what you are somewhat suggesting is that some things in ResourceSpec, such as the process count, should be in JobAttributes. I would make me feel better about the lone duration problem...

I would prefer that indeed - IMHO, the `ResourceSpec` is really about physical resources provided by the system, `JobAttributes` are about how those resources are being used.  Which is also why I agree with your earlier statement: time plays a double role: it (a) specifies how long the physical resources are requested for, and (b) for how long the job is expected to use those resources.  Ideally that is the same thing - but in reality it often is not.

The way we slice and dice attributes was informed by Flux mostly, IIRC - the Flux folx may have had good reasons to add the process count to the resource spec.  That may have been historic reasons though I guess: basically all batch systems handle it that way.

Aaaanyway, as said, I am also a fan of not changing things on API level unless there is a *compelling* reason, i.e. a better reason than 'it looks a bit nicer' or 'is a bit more consistent'.  ;-)

**Comment by hategan** [comment]
> I would prefer that indeed - IMHO, the ResourceSpec is really about physical resources provided by the system, JobAttributes are about how those resources are being used. Which is also why I agree with your earlier statement: time plays a double role: it (a) specifies how long the physical resources are requested for, and (b) for how long the job is expected to use those resources. Ideally that is the same thing - but in reality it often is not.

In theory it is very much not. Nor is it in practice, unless your job gets killed by the system because you hit the time limit on your allocation. You almost always want to allocate more time, by a comfortable margin, than what your job actually needs in practice. And that's because it's not an exact science, and the cost of asking for more time is minimal compared to the cost of having your job killed just as it was about to finish.

> The way we slice and dice attributes was informed by Flux mostly, IIRC - the Flux folx may have had good reasons to add the process count to the resource spec. That may have been historic reasons though I guess: basically all batch systems handle it that way.

We did the same in cog/swift, so maybe it's not flux's fault :). How did it work in SAGA?

**Comment by andre-merzky** [comment]
SAGA flattens everything into one set of attributes... :-P  RCT on the other hand also separates resource request from job properties: once you try to run two jobs within the same allocation, the separation of concerns becomes somewhat more obvious...

**Comment by hategan** [comment]
Ok, so maybe we lump this into a bigger effort to rework the balance between attributes and resource specification? Not sure it will happen before 1.0 though.

**Comment by andre-merzky** [comment]
Indeed, I would not delay 1.0 for this.  Maybe level-2 is a good point to reconsider the distribution?

**Comment by hategan** [comment]
I've opened #176 to track the larger issue.

@frobnitzem, I know this isn't quite a fix, but are you OK with leaving things as they are for now and working on a more general solution for #176?

**Comment by frobnitzem** [comment]
Yes - it seems reasonable that changing specs shouldn't be done hastily.
