### ISSUE TITLE
state model

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#24]
I added a state model diagram [here](https://github.com/ExaWorks/job-api-spec/blob/state_model/diagrams/state%20model.svg) which attempts to cover all states listed in the spec.  It does not include the state transitions to `FAILED` and `CANCELED` right now, for simplicity.

I think we should remove `RESUMED`.  `RESUMED` basically means that the job is `ACTIVE` again, just that the route to that state is different.  A state should not be  defined by the object history, but by it's current, well, state.

I would also suggest to remove `SUSPENDED` for now, since we don't have a `job.suspend()` call.  The only way to reach `SUSPENDED` would be a system suspend, and that is rare, and I don't think we have a use case for it.

**Comment by andre-merzky** [comment]
Another comment on the state model: we have the `IsGreaterThan` method.  It defines, that if a comparison is valid, then all intermediate state transitions are considered to have happened.

I think that does not work for `FAILED` and `CANCELED`: both are final, and thus `FAILED > ACTIVE` must be true.  But a job can enter `FAILED` without ever becoming `ACTIVE`, so the assumption that all intermediate states happened will not hold.

Further, this will break down if we ever re-add `SUSPENDED`, since `ACTIVE > SUSPENDED`  and `SUSPENDED > ACTIVE` must both be true, and both be false at the same time.

I would suggest to remove the method, and to state:
```
The `NEW` state is the only initial state.  `COMPLETED`, `FAILED` and `CANCELED` are all final states.  `COMPLETED` and `FAILED` can be reached from any other, non-final state.  The normal state transition is `NEW -> QUEUED -> ACTIVE -> COMPLETED`.  No other state transitions are allowed.
```

We could add `isFinal` instead to make that check easier (as a shortcut of `job.state in [completed, failed, canceled]`.

**Comment by hategan** [comment]
> Another comment on the state model: we have the `IsGreaterThan` method. It defines, that if a comparison is valid, then all intermediate state transitions are considered to have happened.

I am not sure I understand this part.

> 
> I think that does not work for `FAILED` and `CANCELED`: both are final, and thus `FAILED > ACTIVE` must be true. But a job can enter `FAILED` without ever becoming `ACTIVE`, so the assumption that all intermediate states happened will not hold.

I did mean FAILED > ACTIVE, but I can see how a job can jump from QUEUED to FAILED. So I don't think FAILED > ACTIVE is correct.

> 
> Further, this will break down if we ever re-add `SUSPENDED`, since `ACTIVE > SUSPENDED` and `SUSPENDED > ACTIVE` must both be true, and both be false at the same time.

The reason why ACTIVE and SUSPENDED are not comparable is exactly because of what you describe. And the order in the doc takes this into account. That said, the method is wrong, since it returns a strict boolean, but it needs to return something else when two states are not comparable.

> 
> I would suggest to remove the method, and to state:
> 
> ```
> The `NEW` state is the only initial state.  `COMPLETED`, `FAILED`
> and `CANCELED` are all final states.  `COMPLETED` and `FAILED` 
> can be reached from any other, non-final state.  The normal state 
> transition is `NEW -> QUEUED -> ACTIVE -> COMPLETED`.  
> No other state transitions are allowed.
> ```

Can we really say that no other state transitions are allowed? We can have NEW -> QUEUED -> FAILED, NEW -> QUEUED -> CANCELED, but not NEW -> ACTIVE -> QUEUED -> COMPLETED. 

> 
> or something similar. I am not sure if you see a use case where an application would receive a state (say `ACTIVE`) and would then need to find out if that happened before or after, say, `QUEUED` - the application would have received a `QUEUED` state update earlier already, and would simply know about the progression...

This is to deal with events received out-of-order so that the job doesn't become QUEUED after being ACTIVE.

Overall, I see your point. You can't really model this with partially ordered sets and do so with a straight face. The proper way is with a directed graph representing a state diagram. The only problem is that it makes a lot of things harder, such as filling-in missing states: you have to find a pah, presumably the shortest path between current and new state, dealing with loops, etc., and that's not as simple as calling pred() a few times.

So either we simplify the state model to be a poset, or we do it with a directed graph. I was trying to go with the former, but I think I failed.

**Comment by andre-merzky** [comment]
Yeah, I think a directed graph is intuitive and also custom for state models.  The only other representation I have seen used in the past is transition tables - they are nicely explicit but a bit more cumbersome to use.  [Reference](https://en.wikipedia.org/wiki/Finite-state_machine#Representations)

**Comment by andre-merzky** [comment]
> This is to deal with events received out-of-order so that the job doesn't become QUEUED after being ACTIVE.

I am missing some point.  We require that the implementation is filling in missing events - so how can events arrive out of order?  I would assume that is taken care of by the implementation?  From the current spec:
```
Furthermore, implementations must, to the extent possible, simulate
missing states. For example, if the implementation polls a LRM queue
infrequently enough such that the active state of a job is skipped
between two polling rounds, the job would otherwise appear to have jumped
from a `QUEUED` state to a `COMPLETED` state. However, implementations
can introduce a synthetic `ACTIVE` state change.
```

**Comment by hategan** [comment]
Wait, stop the presses!

If an implementation is to be able to reject states that cannot happen after some other states, then it needs to have, in some way, a function that decides, for every state A and B, if A can occur before the B. That is, if there is a path in the state diagram between A and B: `bool pathExists(A, B)`.

Now, `pathExists` is a binary (has two arguments) relation (is either true or not). If we extend this a bit to also say that A can occur before A, knowing that duplicate events are not possible then:
- the relation is transitive: if there is a path between A and B and there is a path between B and C, then there is a path between A and C
- reflexive: pathExists(A, A), for every A, as agreed above
- antisymmetric: if pathExists(A, B) AND pathExists(B, A) then B == A.

pathExists() is therefore an ordering relation. Unlike what is in the original doc, it is a total ordering relation. Every two elements can be compared. There is also some other aspects, such as ACTIVE == SUSPENDED. This if fine. If we get ACTIVE after SUSPENDED or SUSPENDED after ACTIVE, that is OK, and pathExists tells us that.

Note that `pathExists` or some form of it needs to be written by an implementation if it is to correctly implement rejection of impossible transitions.

A similar thing goes for implementing synthetic events. In order to do so, if a job is in state A and receives an event B, then it must generate synthetic events going in **some** path between A and B in the state diagram. Presumably, one would make a choice of using not some arbitrary path, but something like the **shortest** path. So let's assume that from now on and simply call it **path**. So now, we need some function which, given that we are in state A and we got event B and we have so far traversed things up to C, gives us the next state: `state pred(A, C, B)`.

Now, because we chose shortest paths, or some consistent path, it does not change as we move through it. In other words, if the shortest path between A and B goes through C then it contains the shortest path from A to C and the shortest path from C to B. So it is sufficient to have `state pred(A, C)` which returns the next step in the shortest path from A to C (or C to A in reverse).

Again, an implementation has to, in some for or another, end up writing something like `pred` if it is to correctly generate synthetic events.

I am of the very strong opinion that we should codify the result of this discussion, otherwise we run the risk of having implementors go through the same discussion and running the risk of writing an incomplete and broken solution, just as we were about to do.

**Comment by hategan** [comment]
> > This is to deal with events received out-of-order so that the job doesn't become QUEUED after being ACTIVE.
> 
> I am missing some point. We require that the implementation is filling in missing events - so how can events arrive out of order? I would assume that is taken care of by the implementation? From the current spec:
> 

Read as "This is so that the implementation can deal with events received out-of-order...". E.g., discard a QUEUED event received after a COMPLETED event.

**Comment by andre-merzky** [comment]
After discussion on today's call, we favor the state model depicted [here](https://docs.google.com/drawings/d/13Vh0UjR0Ribnf9Q0BDVCNOwHwscZhMCk0jxSKp2G0rM)

**Comment by hategan** [comment]
> After discussion on today's call, we favor the state model depicted [here](https://docs.google.com/drawings/d/13Vh0UjR0Ribnf9Q0BDVCNOwHwscZhMCk0jxSKp2G0rM)

I think that's beautiful.

**Comment by andre-merzky** [comment]
State model has been added.
