### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#34]
One of the hardest problems in Comp Sci.....what do we call this thing?

**Comment by danlaney** [comment]
SiPPY:  Saga Plus Plus Yay!  --- Shantenu's idea, posting for him in case he is busy

**Comment by andre-merzky** [comment]
> SiPPY: Saga Plus Plus Yay! --- Shantenu's idea, posting for him in case he is busy

Yeah, that sounds *exactly* like Shantenu :-P

> One of the hardest problems in Comp Sci.....what do we call this thing?

I think somebody mentioned on a very early discussion on the topic that we may want to consider dropping the name SAGA, and the argument was that it may have too much ballast accumulated.

I would add another argument to that point: the API will be very different from the SAGA spec,  so much really that it is actually hard to justify to keep the name.   How would we otherwise communicate why we change state model, state names, object names, async model, error types, callback mechanism.... like, *_everything_* between two versions of an API.  So I'd be in favour of a new name.  Which does, of course, only support Dong's initial statement :-D

**Comment by danlaney** [comment]
Coolship:  https://en.wikipedia.org/wiki/Coolship
Its a bit flat space (kinda like an allocation?) where wild yeast (random workflow systems) can inoculate the wort (do useful things) to make great science (good beer!).

**Comment by hategan** [comment]
> Coolship: https://en.wikipedia.org/wiki/Coolship
> Its a bit flat space (kinda like an allocation?) where wild yeast (random workflow systems) can inoculate the wort (do useful things) to make great beer (great science!).

Dangerous. Would get us into wine vs. beer arguments, and from there it's a slippery slope to tabs vs. spaces, emacs vs. vi, perturbation theory vs. path integral, etc.

**Comment by dongahn** [comment]
We can use SiPPY just not the suggested backcronym?

**Comment by danlaney** [comment]
SiPPI: Scheduler Parsimonious Programming Interface

**Comment by SteVwonder** [comment]
> SiPPI: Scheduler Parsimonious Programming Interface

I like it. Now we just need a SiPPI project with the name CUP and we are all set!

**Comment by dongahn** [comment]
Component-wide Universal Plug-and-play

**Comment by andre-merzky** [comment]
> We can use SiPPY just not the suggested backcronym?

That  would work for me.

**Comment by SteVwonder** [comment]
Relevant, random words from my brainstorming session (plus some from @kylechard on today's call):

- Common, Portable, Universal, Lightweight
- Job, Task, Work, Resource
- API, Specification, Layer, Interface
- Submission, Management
- Tracking, Taming, Injecting
- User, System
- Distributed, Parallel

**Comment by SteVwonder** [comment]
One option discussed on today's call:

PSI - Portable Submission Interface

**Comment by danlaney** [comment]
SAISON: Simple Application Interface for Scheduler/ing O? N?

**Comment by SteVwonder** [comment]
Based on the conversations in slack, I think we are converging on @hategan's suggestion of J/ψ, which expands to J/PSI, which expands to the Portable Submission Interface for Jobs.  It is pronounced like "Jay-Sigh" (or  ˈdʒeɪ ˈsaɪ if you know [IPA](https://en.wikipedia.org/wiki/Help:IPA/English)).  The code prefix would be "jpsi".  If anyone has any objections, please raise them now.  Otherwise, I think we plan to move forward with this name.
