### ISSUE TITLE
Accomodating short-lived clients

### ISSUE THREAD

**Issue by ejfried** [ExaWorks/job-api-spec#41]
Some jobs remain in queue and/or run for days. It may not be possible (or allowed)  for a client program to stay up for the whole time, so there should be a mechanism to submit, query, and reap jobs from multiple distinct executions of a client program, spread over time and/or space.  I can think of two ways to do this, either:

1. The JobExecutor could have  query methods returning Job objects,  or
2. Job could have a constructor or a factory method to create live Job objects from the Job id.

**Comment by andre-merzky** [comment]
I support this request, and would suggest to add:

```py
JobExecutor.list() -- returns list of job IDs known to the executor (qstat -u <user_id>
JobExecutor.get(uids) -- returns a list of job instances for the give job IDs
```

**Comment by hategan** [comment]
I also am on board with the idea, but I would propose methods closer to the original comment:

`Job JobExecutor.attach(String nativeId)`. One would then query the status of the job using Job.getStatus().

I would also suggest making the `nativeId` a first class citizen, by adding `Job.getNativeId()`, which would be populated when the job makes it to a LRM queue.

Depending on what we ultimately decide about bulk calls (i.e., push this into the implementation and leave the API alone or not) we may also do `Job[] JobExecutor.attach(String[] nativeIds)` in order to avoid invoking `qstat` for each job being attached. We may have to augment the state model with an ATTACHED state, so that proper notification when an async attach operation completes is provided to the client.

**Comment by andre-merzky** [comment]
> We may have to augment the state model with an ATTACHED state, so that proper notification when an async attach operation completes is provided to the client.

Oh, I don't think that would work: how would a job which is active differ when it is submitted and changes to `ACTIVE` and when I give a job ID and find it active?  It's still an active job.  Moreover, two clients looking at the same job would find it in different states (like, the original submitting application has `ACTIVE`, and a portal watching progress sees `ATTACHED`).

I think a state name should not reflect state history, in the sense it does not matter how the job instance got into that state, it matters that the job *is* in that state.

**Comment by andre-merzky** [comment]
naming: `attach` that works well for me.  I am also on board to have an explicit query for the native ID.

> in order to avoid invoking qstat for each job being attached

`qstat` output can be cached, it will not be required to invoke it for every new job.  Having said that, I am all for bulk-enabling the full interface (where sensible) instead of only parts of it.

**Comment by hategan** [comment]
> > We may have to augment the state model with an ATTACHED state, so that proper notification when an async attach operation completes is provided to the client.
> 
> Oh, I don't think that would work: how would a job which is active differ when it is submitted and changes to `ACTIVE` and when I give a job ID and find it active? It's still an active job. Moreover, two clients looking at the same job would find it in different states (like, the original submitting application has `ACTIVE`, and a portal watching progress sees `ATTACHED`).

`ATTACHED` would be immediately followed by another status update with the actual job state.

But I think you are right in that there is no need for an explicit `ATTACHED` state. One can simply wait for a non-initial state.
My worry was about users calling `Job.getStatus()` immediately after calling `attach()`, without the adapter having had time to query the LRM for status yet.

We need to think about this a bit, since returning a job is probably a bad idea if you want to add a callback. It would lead to possible race conditions. So maybe `JobExecutor.attach(Job job, String nativeId)` would be a better choice, such that client code can add the callback before invoking `attach()`.

> 
> I think a state name should not reflect state history, in the sense it does not matter how the job instance got into that state, it matters that the job _is_ in that state.

I agree. However, one can consider the state as the state of the `Job` object. In many ways, a `SUBMITTED` state, should it exist, would be similar to `ATTACHED` in that it would not represent an actual state of the job, by an internal state in the implementation of the API. But again, I agree that `ATTACHED` is likely useless.

**Comment by hategan** [comment]
> [...]
> 
> `qstat` output can be cached, it will not be required to invoke it for every new job. Having said that, I am all for bulk-enabling the full interface (where sensible) instead of only parts of it.

I personally like the caching suggestion better.

**Comment by andre-merzky** [comment]
@hategan : Thanks for the details, now I see what you mean with `ATTACHED`.  I would not mind adding another initial state -- probably `ATTACH` though, as from what you describe, it covers the time until the backend actually completed the re-attachment?  

>> [cache qstat output / bulk API]
> I personally like the caching suggestion better.

I don't think they are exclusive - caching is an implementation choice, bulking (in this context) an API paradigm.

**Comment by hategan** [comment]
> I don't think they are exclusive - caching is an implementation choice, bulking (in this context) an API paradigm.

Right. But it seems to be one of those trade-offs that simplifies the interface at the expense of the implementation without changing performance.

**Comment by andre-merzky** [comment]
The change in complexity from
```
Job JobExecutor.attach(String nativeId)
```
to
```
Job[] JobExecutor.attach(String[] nativeIds)
```
seems definitely manageable, specifically with the trivial implementation
```py
def attach(self, native_ids):
    return [self._attach(id) for id in native_ids]
```
so I would not worry about that.  Here I would value consistency more: submit, cancel, attach, etc should all take bulks IMHO.

**Comment by hategan** [comment]
Consistency can also go the other way.

I mean I'd rather have what you proposed (caching) and no bulk `attach()` and, to get consistency, also remove the bulk `submit()` and have a time-window in the implementation if the implementation knows that it can benefit from clustering/bulking. Or really, just whatever the implementation thinks is necessary to get good performance.

**Comment by andre-merzky** [comment]
Just leaving a note that the bulk discussion has been resolved in a different thread.  This issue results in the suggestion to add

  - job.getNativeId()
  - jobExecutor.attach(nativeID) -> job
  - jobExecutor.list() -> list of nativeIDs

**Comment by andre-merzky** [comment]
We specified `attach()` and `list()` by now, thus closing this issue.
