### ISSUE TITLE
Clarification on spec versioning

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#78]
The specification explicitly references the Flux JobSpec version 1, and uses it as basis for the job specification:

> This describes the version 1 of the job specification, which represents a request to run exactly one program. This version is based heavily on Flux's Jobspec V1

However, the specification has a `ResourceSpecificationV1`, but not a `JobSpecificationV1`.  I miss a clarification on how the versioning mentioned in the text is related to the versioning (or lack of) in the `ResourceSpecifiction` and `JobSpecification` classes.

**Comment by hategan** [comment]
JobSpec does not have a version. There is nothing expected to change in that part of the API. ResourceSpec does. We discussed the spectrum and decided we'll start with a simple thing.

ResourceSpec is an abstract class. It has one concrete implementation for now: ResourceSpecV1.

**Comment by andre-merzky** [comment]
Again, the document states explicitly:

> This describes the version 1 of the job specification

which implies that it **does** have a version.  The statement may be incorrect, so either the text or the versioning need fixing I would assume.  Am I missing something?

**Comment by SteVwonder** [comment]
> JobSpec does not have a version. There is nothing expected to change in that part of the API. ResourceSpec is an abstract class. It has one concrete implementation for now: ResourceSpecV1.

The canonical version of the Flux Jobspec supports multiple executables/arguments per jobspec file (Flux Jobspec V2 won't support it though).  If we don't want to support that multiple executable functionality in J/PSI, then I think the API breakdown you listed above will work and we can change the quoted text to remove the reference to "version 1".  If we want to support multiple executables eventually, we will need to add a JobSpecV1 (since it will be an API breakage to `setExecutable`).

**Comment by hategan** [comment]
> > obSpec does not have a version. There is nothing expected to change in that part of the API. ResourceSpec is an abstract class. It has one concrete implementation for now: ResourceSpecV1.
> 
> The canonical version of the Flux Jobspec supports multiple executables/arguments per jobspec file (Flux Jobspec V2 won't support it though). If we don't want to support that multiple executable functionality in J/PSI, then I think the API breakdown you listed above will work and we can change the quoted text to remove the reference to "version 1". If we want to support multiple executables eventually, we will need to add a JobSpecV1 (since it will be an API breakage to `setExecutable`).

JPSI Jobspec != Flux Jobspec. More like JPSI ResourceSpec = Flux Jobspec.

The appendix uses the word "Jobspec" to refer to Flux Jobspec without explicitly stating so. But, because of the context, it sounds like it's talking about JPSI Jobspec. Of course, Flux Jobspec V1 ~ JPSI Resourcespec V1, so it's all fine. But, with the wrong interpretation of "Jobspec" (JPSI) and talk about a Jobspec version, it sounds like JPSI is missing something.

**Comment by hategan** [comment]
@SteVwonder, can you update the serialization appendix to make it more clear what is what?

**Comment by SteVwonder** [comment]
I noticed that we do have the `version` key in the YAML, which is currently undefined in the appendix.  While we might not have any current plans to add new versions of the J/PSI jobspec, it seems prudent to leave the key in case we find a need to in the future.  I just want to clarify, are others OK with leaving the `version` key in the J/PSI jobspec YAML?

**Comment by hategan** [comment]
In a sense, I'd be inclined to say that the the structure of JPSI spec classes implicitly defines a YAML (or any other tree-like format) structure and that any serialization format that does not conform to that structure is likely a barrier for adoption and/or implementation simplicity.

But since we deviate quite heavily from the above, I do not think that a version key in the YAML spec would make much of a difference, so I am OK with it.
